###
#  Ansible vars file sample for role configuration varibles: basic ONTAP cluster & vserver config
#  
###

###
# Role-Based Configuration: Cluster
###

# VSIM license's code
# license_codes: QDDSVRRRYVHXCFABGAAAAAAAAAAA,MBXNQRRRYVHXCFABGAAAAAAAAAAA,ANGJKUNFXMSMUCEZFAAAAAAAAAAA,UFTUNUNFXMSMUCEZFAAAAAAAAAAA
license_codes: "{{ licenses }}"

disks:  # disks module assigns all visible disks to a node. This may be done during Day 0 Installation process
- "{{ cluster }}-01"
- "{{ cluster }}-02"

dns:    # Set DNS for Cluster
- { dns_domains: "{{ dns_domain }}", dns_nameservers: "{{ dns_srvrs }}" }

ntp:    # Set NTP Server (requires the cluster to have DNS set)
- { server_name: "{{ time }}", version: auto }

aggrs:  # Create one or more Aggregates.
- { name: "{{ cluster.aggr }}_01_aggr1", node: "{{ cluster }}-01", disk_count: 40, max_raid: 20 }
- { name: "{{ cluster.aggr }}_02_aggr1", node: "{{ cluster }}-02", disk_count: 40, max_raid: 20 }

ports:  # Set MTU for ports
- { node: "{{ cluster }}-01", port: e0d, mtu: 1500, flowcontrol: none }
- { node: "{{ cluster }}-01", port: e0e, mtu: 1500, flowcontrol: none }
- { node: "{{ cluster }}-01", port: e3a, mtu: 1500, flowcontrol: none }
- { node: "{{ cluster }}-01", port: e3b, mtu: 1500, flowcontrol: none }
- { node: "{{ cluster }}-02", port: e0d, mtu: 1500, flowcontrol: none }
- { node: "{{ cluster }}-02", port: e0e, mtu: 1500, flowcontrol: none }
- { node: "{{ cluster }}-02", port: e3a, mtu: 1500, flowcontrol: none }
- { node: "{{ cluster }}-02", port: e3b, mtu: 1500, flowcontrol: none }

ifgrps:  # Create and add ports to Interface Groups.
- { name: a0a, node: "{{ cluster }}-01", ports: "{{ ifgrp_ports }}", mode: multimode_lacp, mtu: 9000 }
- { name: a0a, node: "{{ cluster }}-02", ports: "{{ ifgrp_ports }}", mode: multimode_lacp, mtu: 9000 }

vlans:  # Create vlans on LIFS
# - { id: "{{ vlan_id }}", node: "{{ cluster }}-01", parent: a0a }
# - { id: "{{ vlan_id }}", node: "{{ cluster }}-02", parent: a0a }

bcasts:  # Create Broadcast domains
- { name: "{{ bd.nas }}", mtu: 1500, ipspace: default,
    ports: "{{ cluster }}-01:a0a,{{ cluster }}-02:a0a" }
- { name: "{{ bd.mgmt }}", mtu: 1500, ipspace: default,
    ports: '{{ cluster }}-01:e0M,{{ cluster }}-02:e0M,{{ cluster }}-01:e0e,{{ cluster }}-02:e0e' }

inters: # Create intercluster lifs for SnapMirror.
- { name: "{{ cluster }}-01_icl1", address: "{{ node1.icl }}", netmask: "{{ svm_netmask }}", 
    node: "{{ cluster }}-01", port: e0d }
- { name: "{{ cluster }}-02_icl2", address: "{{ node2.icl }}", netmask: "{{ svm_netmask }}", 
    node: "{{ cluster }}-02", port: e0d }


###
# Role-Based Configuration: Vserver (SVM)
###

vservers:  # Vservers to create # aggr_list is optional.  If not specified, defaults to all aggregates.
- { name: "{{ svm }}", aggr: "{{ cluster.aggr }}_01_aggr1", protocol: nfs, rootvol: "{{ svm.root }}", aggr_list: "{{ cluster.aggr }}_01_aggr1,{{ cluster.aggr }}_02_aggr1" }

vserver_dns:  # DNS at the Vserver level
- { vserver: "{{ svm }}", dns_domains: "{{ dns_domain }}", dns_nameservers: "{{ dns_srvrs }}" }

lifs:  # interfaces for the Vservers being created
- { name: "{{ svm }}_data1", vserver: "{{ svm }}", node: "{{ cluster }}-01", port: a0a, protocol: nfs, address: "{{ node1.svm_lif1 }}", netmask: "{{ svm_netmask }}" }
- { name: "{{ svm }}_data2", vserver: "{{ svm }}", node: "{{ cluster }}-02", port: a0a, protocol: nfs, address: "{{ node1.svm_lif2 }}", netmask: "{{ svm_netmask }}" }

gateway:  # To configure the default route/gateway for the vservers
- { vserver: "{{ svm }}", destination: 0.0.0.0/0, gateway: "{{ svm_gateway }}" }
