###
#  Ansible vars file sample for a basic ONTAP cluster & vserver
#
###

###
# Varibles for ONTAP cluster setup & config
cluster:          sandbox
clus:
  name:           "{{ cluster }}"
  loc:            VSIM                   # 'system snmp location'
  mgmt:           192.168.7.200
  netmask:        255.255.255.0
  gateway:        192.168.7.1
  aggr:           "{{ cluster | replace('-','_') }}"  # Replaces - with _

# Node & SVM Network IP address Information
node1:
  node_mgmt_ip:   192.168.7.201
  icl:            192.168.7.202
  svm_lif1:       192.168.7.205
node2:
  node_mgmt_ip:   192.168.7.203
  icl:            192.168.7.204
  svm_lif2:       192.168.7.206

# Authentification Defaults
netapp_hostname:  "{{ clus.mgmt }}"
netapp_username:  admin
netapp_password:  netapp1234     # Remove to use vars_prompt or vault password
validate_certs:   false          # Set to bypass security error due to self-signed certs

###
# DNS Services Settings
dns_domain:       example.local
dns_srvrs:        192.168.7.3

###
# NTP & Timezone Settings
time:             time.nist.gov
tzone:            'US/Pacific'  #  <Area/Location Timezone> - Specified in the Olson format
# tzone:          'ETC/GMT'     #  <Area/Location Timezone> - Specified in the Olson format

###
# Broadcast Domain name varibles
bd:
  mgmt:         mgmt
  nas:          data

# Broadcast-domain split: Active Management ports
bcd:
  split_ports:
  # - origin_bd:    Default
  #   new_bd:       "{{ bd.mgmt }}"
  #   ports:        '["{{ cluster }}-01:e0M", "{{ cluster }}-02:e0M"]'
  - origin_bd:  Default
    new_bd:     "{{ bd.mgmt }}"
    ports:      '["{{ clus.name }}-01:e0c", "{{ clus.name }}-02:e0c"]'

###
# Network Topoly / Link Standard
# Networking Varibles - Update port members for 'ifgrp' config below
ifgrp_ports:    "e0f"
vlan_id:        42          # Replace with VLAN ID

###
# Autosupport Configuration Varibles
asup:

  # Standard Config varibles
  proxy_url:
  transport:    smtp
  noteto:       admin@example.local
  mailhosts:    192.168.7.3
  hostsubj:     true
  to:           netapp_admin@example.local
  from:         '{{ cluster }}@{{ dns_domain }}'
  partner:

  # Node Specific Config parameters - node list
asup_config:
- node:       '{{ clus.name }}-01'
  proxy_url:  '{{ asup.proxy_url }}'
  transport:  '{{ asup.transport }}'
  mailhosts:  '{{ asup.mailhosts }}'
  hostsubj:   '{{ asup.hostsubj }}'
  from:       '{{ asup.from }}'
  to:         '{{ asup.to }}'
  noteto:     '{{ asup.noteto }}'
  partner:    '{{ asup.partner }}'
- node:       '{{ cluster }}-02'
  proxy_url:  '{{ asup.proxy_url }}'
  transport:  '{{ asup.transport }}'
  mailhosts:  '{{ asup.mailhosts }}'
  hostsubj:   '{{ asup.hostsubj }}'
  from:       '{{ asup.from }}'
  to:         '{{ asup.to }}'
  noteto:     '{{ asup.noteto }}'
  partner:    '{{ asup.partner }}'

###
# SVM Configuration Settings
svm:            ontap-vs01
svm_root:       "{{ svm | replace('-','_') }}"
svm_aggrs:      "{{ clus.aggr }}_01_aggr1,{{ clus.aggr }}_02_aggr1"
svm_dns_domain: example.local
svm_dns_srvrs:  192.168.7.3
svm_netmask:    "{{ clus.netmask }}"    # Replace with IP if not the same
svm_gateway:    "{{ clus.gateway }}"    # Replace with IP if not the same

# svm:            ontapvs01
#   root:         "{{ svm | replace('-','_') }}"
#   netmask:      "{{ cluster_netmask }}"    # Replace with IP if not the same
#   gateway:      "{{ cluster_gateway }}"    # Replace with IP if not the same
#   aggr_list:    '[  ]'
#   export_policy:
#   - name:  'Data'
#     client_match:
#     index:
#     ro_rule:
#     rw_rule:
#     super_user_security:

###
# Export-Policy Management
# Note: Replace networks that are valid to the environment & adjust as needed
###

svm_export_policy_name:
- { svm: "{{ svm }}", name: 'Data' }

export_policy_rules_list:
- { name: 'default', svm: "{{ svm }}", client_match: '192.168.7.122', protocol: nfs, ro_rule: 'sys', rw_rule: 'sys', super_user_security: 'sys' }
- { name: 'default', svm: "{{ svm }}", client_match: '192.168.7.0/24', protocol: any, ro_rule: 'any', rw_rule: 'none', super_user_security: 'none' }
- { name: 'Data', svm: "{{ svm }}", client_match: '192.168.7.0/24', protocol: nfs, ro_rule: 'any', rw_rule: 'any', super_user_security: 'sys' }
- { name: 'Data', svm: "{{ svm }}", client_match: '0.0.0.0/0', protocol: nfs, ro_rule: 'any', rw_rule: 'none', super_user_security: 'none' }

###
# ONTAP Licenses
# Note: VSIM license's code
###
licenses: QDDSVRRRYVHXCFABGAAAAAAAAAAA,MBXNQRRRYVHXCFABGAAAAAAAAAAA,ANGJKUNFXMSMUCEZFAAAAAAAAAAA,UFTUNUNFXMSMUCEZFAAAAAAAAAAA
